# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: resume build

on:
  push:
    paths:
      - '.github/workflows/client-app.yml'
      - 'src/client/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '.parcelrc.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: build
        run: |
          npm ci
          npm run build
      - name: upload app
        uses: actions/upload-artifact@master
        with:
          name: client-app
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: client-app.yml
          workflow_conclusion: success
          branch: master
          name: client-app
      - name: display files
        run: ls -a
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
