# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: resume build

on:
  push:
    paths:
      - '.github/workflows/client-app.yml'
      - 'src/client/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '.parcelrc.json'

env:
  package_id: resume
  package_version: 0.0.0-beta.${{ github.run_number }}
  package_bin: bin
  package_type: zip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: build
        run: |
          npm ci
          npm run build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: client-app
          path: dist
