name: deploy resume

on:
  workflow_run:
    workflows:
      - resume build
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo Hello World
