name: deploy resume

on:
  workflow_run:
    workflows:
      - resume build
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: download
      - uses: actions/download-artifact@v2
        with:
          name: client-app
      - name: display files
        run: ls -a
