# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]
  #push: 
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

package:
  id: resume
  version: 0.0.0-beta.${{ github.run_number }}

env:
  package_id: resume
  package_version: 0.0.0-beta.${{ github.run_number }}
  package_name: ${{ package.id }}.${{ package.version }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm test
    - run: node octo-pack.js --id ${{ env.package_id }} --v ${{ env.package_version }}
    - name: Upload release pacakge artifact
      uses: actions/upload-artifact@v1
      with:
        name: release ${{ env.package_name }}
        path: bin/${{ env.package_name }}.zip
