# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]
  #push: 
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

env:
  package_id: resume
  package_version: 0.0.0-beta.${{ github.run_number }}
  package_bin: bin
  package_type: zip

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: build
      run: |
        npm ci
        npm run build --if-present
    #npm test
    #- name: package release
    #  run: |
    #    node octo-pack.js --id ${{ env.package_id }} --v ${{ env.package_version }} --output ${{ env.package_bin }}
    #    echo "::set-env name=package_name::$package_id.$package_version"
    #- run: echo "::set-env name=package_path::$package_bin/$package_name.$package_type"
    #- name: Upload release pacakge artifact
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: release ${{ env.package_name }}
    #    path: ${{ env.package_path }}
        #path: bin/${{ env.package_name }}.zip
    #- name: deploy release
    #  run: |
    #    node octo-push.js --path ${{ env.package_path }} --hostname ${{ secrets.OCTO_URL }} --apikey ${{ secrets.OCTO_API_KEY }}
