name: check fastify server

on: ['push']

env:
  PORT: 3000

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: add env configuration
        run: |
          touch .env
          echo KILLONPRINT=true >> .env
          echo PORT=${{env.PORT}} >> .env
          cat .env
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: run server
        run: |
          npm ci
          npm run server &
      - name: check connection
        run: curl -I http://localhost:${{env.PORT}}/connected
